### ISSUE TITLE
Is is possible to uses pre-defined models of activities to specify the order of events?

### ISSUE THREAD

**Issue by longnp93** [openshs/openshs#5]
Hi @nashamri ,

Is is possible to uses pre-defined models of activities to specify the order of events as model-based approach? For example, I want to customize a temperature sensor whose value will increase when I turn on a gas range in the kitchen?

Have you developed temperature sensor in your current version? Or do you have any ideas on determine the context of temperature sensor value?

Thanks.

**Comment by nashamri** [comment]
> Is is possible to uses pre-defined models of activities to specify the order of events as model-based approach?

It can be done, but it wasn't the intention of this project. As explained in the [paper](http://www.mdpi.com/1424-8220/17/5/1003) the idea is to have a hybrid solution of model-based and interactive approaches. You let the participants simulate their activities in real-time and the "replication algorithm" will generate more samples based on the recorded "interactive simulations". So, in short, you can do it because of how flexible the tool is, but you need to program that feature as it wasn't one of the goals of OpenSHS :smile: 

> Have you developed temperature sensor in your current version? Or do you have any ideas on determine the context of temperature sensor value?

Unfortunately no I haven't, my use case was to develop binary sensors and I didn't have any "scalar-valued sensors". It can be done under the current code base but it needs more development for several parts of the system. For instance, the way that the "replication algorithm" I think need to be modified to incorporate scalar values. That's what comes to my mind, and there might be other areas that need modifications.

Hope this helps @longnp93 :smile:

**Comment by longnp93** [comment]
Hi @nashamri,

Thank you for your response. Unfortunately OpenSHS does not currently offer features that I expect. If OpenSHS is able to provide predefined model of activities and scalar-value sensors, OpenSHS would be powerful and much useful for real end-user like me. Because it is exactly what I want to simulate a smart home.

Thank you @nashamri

**Comment by nashamri** [comment]
@longnp93 you are welcomed. Hopefully, in the future that will come :smile:
Meanwhile, maybe this [paper](http://www.mdpi.com/1424-8220/17/11/2562/html) could help your use case.
