### ISSUE TITLE
Can't start simulation after installation

### ISSUE THREAD

**Issue by williamregnart** [openshs/openshs#7]
Hi,

I followed all steps to install openSHS on Windows with the video in the README file. But when I want to launch a simulation, I have this error : 

![Capture](https://user-images.githubusercontent.com/32563184/59783987-4ffb8700-92b9-11e9-93ef-d15ddc66d4cd.PNG)

I don't how to resolve it, can someone help me please ?

**Comment by houssamkanso** [comment]
Hi, I am facing the same problem.

**Comment by nashamri** [comment]
Hello there,
I think this happen becasue Windows doesn't allow file names with colons in them. I'll try to fix it.

**Comment by nashamri** [comment]
@houssamkanso can you try it now, I dont have access to a windows machine currently, but hopefully this will fix it.

**Comment by houssamkanso** [comment]
Thank you @nashamri,
- Actually, in my case, I was able to open the simulation finally by entering the starting time manually with the **older version**.
I have typed **2016-02-01 08:00:00** then **ENTER** instead of just pressing **ENTER**.
However, when I press **P** to launch the simulation nothing happens but I think this is another issue.

- With the new commit: I am still facing a problem similar to @williamregnart, and when I enter the starting time manually I get the following error:  **Error: Please enter a valid datetime**

**Comment by nashamri** [comment]
You probably need to enter the date using the new format (e.g. 2016-02-01 08-00-00), notice the hyphens instead of colons between the hours, minutes and seconds. And please let me know if this works.

**Comment by houssamkanso** [comment]
I could launch it by doing what you proposed 👍
```
./openshs start -c morning
Starting the morning context.
What's the starting time? [2016-02-01 08:00:00]: 2016-02-01 08-00-00
```
However, when I press **P** nothing happens :(

**Comment by nashamri** [comment]
@houssamkanso I just tried it on windows and when I press 'P' the simulation starts. What version of blender are you using?

**Comment by houssamkanso** [comment]
I am using version 2.93

**Comment by nashamri** [comment]
That's the issue, after blender 2.7 the blender team removed the blender game engine which this project relies on. You probably missed this note in the readme file:
https://github.com/openshs/openshs#note-this-project-requires-blender-27-or-less
